[package]
name = "partials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avdl-rs = {path = "../.."}
apache-avro = "0.14.0"
